#服务端口
server:
  port: 6001

#应用名称及验证账号
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liubintao/spring-cloud-repo
          username:
          password:
          #默认是秒，因为git慢
          timeout: 15

#注册中心
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://root:root@eureka-7900:7900/eureka/
  instance:
    hostname: localhost
    instance-id: config-server

management:
  endpoints:
    web:
      exposure:
        #yml加双引号，properties不用加
        include: "*"